CREATE TABLE IF NOT EXISTS `HistoricalMatch` (
  `id` VARCHAR(30) NOT NULL,
  `source` VARCHAR(30) NOT NULL DEFAULT 'cricsheet',
  `sourceMatchId` VARCHAR(120) NOT NULL,
  `startedAt` DATETIME(3) NULL,
  `season` VARCHAR(40) NULL,
  `matchType` VARCHAR(20) NULL,
  `eventName` VARCHAR(200) NULL,
  `eventNameKey` VARCHAR(200) NULL,
  `venue` VARCHAR(200) NULL,
  `venueKey` VARCHAR(200) NULL,
  `city` VARCHAR(120) NULL,
  `teamA` VARCHAR(120) NOT NULL,
  `teamAKey` VARCHAR(120) NOT NULL,
  `teamB` VARCHAR(120) NOT NULL,
  `teamBKey` VARCHAR(120) NOT NULL,
  `winner` VARCHAR(120) NULL,
  `winnerKey` VARCHAR(120) NULL,
  `resultText` VARCHAR(200) NULL,
  `playerOfMatch` VARCHAR(120) NULL,
  `rawInfo` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `HistoricalMatch_source_sourceMatchId_key` (`source`, `sourceMatchId`),
  KEY `HistoricalMatch_matchType_startedAt_idx` (`matchType`, `startedAt`),
  KEY `HistoricalMatch_team_keys_startedAt_idx` (`teamAKey`, `teamBKey`, `startedAt`),
  KEY `HistoricalMatch_venueKey_startedAt_idx` (`venueKey`, `startedAt`),
  KEY `HistoricalMatch_eventNameKey_idx` (`eventNameKey`)
);

CREATE TABLE IF NOT EXISTS `HistoricalBattingInnings` (
  `id` VARCHAR(30) NOT NULL,
  `matchId` VARCHAR(30) NOT NULL,
  `inningsNumber` INTEGER NOT NULL,
  `inningsTeam` VARCHAR(120) NOT NULL,
  `inningsTeamKey` VARCHAR(120) NOT NULL,
  `oppositionTeam` VARCHAR(120) NULL,
  `oppositionTeamKey` VARCHAR(120) NULL,
  `playerName` VARCHAR(120) NOT NULL,
  `playerNameKey` VARCHAR(120) NOT NULL,
  `playerKey` VARCHAR(120) NOT NULL,
  `runs` INTEGER NOT NULL DEFAULT 0,
  `balls` INTEGER NOT NULL DEFAULT 0,
  `fours` INTEGER NOT NULL DEFAULT 0,
  `sixes` INTEGER NOT NULL DEFAULT 0,
  `strikeRate` DOUBLE NOT NULL DEFAULT 0,
  `dismissalKind` VARCHAR(40) NULL,
  `notOut` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `HistoricalBattingInnings_playerKey_team_idx` (`playerKey`, `inningsTeamKey`),
  KEY `HistoricalBattingInnings_playerNameKey_idx` (`playerNameKey`),
  KEY `HistoricalBattingInnings_match_innings_idx` (`matchId`, `inningsNumber`),
  CONSTRAINT `HistoricalBattingInnings_matchId_fkey`
    FOREIGN KEY (`matchId`) REFERENCES `HistoricalMatch`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `HistoricalBowlingInnings` (
  `id` VARCHAR(30) NOT NULL,
  `matchId` VARCHAR(30) NOT NULL,
  `inningsNumber` INTEGER NOT NULL,
  `inningsTeam` VARCHAR(120) NOT NULL,
  `inningsTeamKey` VARCHAR(120) NOT NULL,
  `oppositionTeam` VARCHAR(120) NULL,
  `oppositionTeamKey` VARCHAR(120) NULL,
  `playerName` VARCHAR(120) NOT NULL,
  `playerNameKey` VARCHAR(120) NOT NULL,
  `playerKey` VARCHAR(120) NOT NULL,
  `overs` DOUBLE NOT NULL DEFAULT 0,
  `maidens` INTEGER NOT NULL DEFAULT 0,
  `runsConceded` INTEGER NOT NULL DEFAULT 0,
  `wickets` INTEGER NOT NULL DEFAULT 0,
  `economy` DOUBLE NOT NULL DEFAULT 0,
  `dotBalls` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `HistoricalBowlingInnings_playerKey_team_idx` (`playerKey`, `inningsTeamKey`),
  KEY `HistoricalBowlingInnings_playerNameKey_idx` (`playerNameKey`),
  KEY `HistoricalBowlingInnings_match_innings_idx` (`matchId`, `inningsNumber`),
  CONSTRAINT `HistoricalBowlingInnings_matchId_fkey`
    FOREIGN KEY (`matchId`) REFERENCES `HistoricalMatch`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `HistoricalPlayerAlias` (
  `id` VARCHAR(30) NOT NULL,
  `source` VARCHAR(30) NOT NULL DEFAULT 'cricsheet',
  `playerKey` VARCHAR(120) NOT NULL,
  `aliasName` VARCHAR(120) NOT NULL,
  `aliasNameKey` VARCHAR(120) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `HistoricalPlayerAlias_playerKey_aliasNameKey_key` (`playerKey`, `aliasNameKey`),
  KEY `HistoricalPlayerAlias_aliasNameKey_idx` (`aliasNameKey`)
);
